CASE 
WHEN country = 'Argentina' THEN 'ARGENTINA'
WHEN country = 'Armenia' THEN 'ARMENIA'
WHEN country = 'Australia' THEN 'AUSTRALIA'
WHEN country = 'Austria' THEN 'AUSTRIA'
WHEN country = 'Azerbaijan' THEN 'AZERBAIJAN'
WHEN country = 'Belgium' THEN 'BELGIUM'
WHEN country = 'Bolivia' THEN 'BOLIVIA'
WHEN country = 'Brazil' THEN 'BRAZIL'
WHEN country = 'Canada' THEN 'CANADA'
WHEN country = 'Chile' THEN 'CHILE'
WHEN country = 'China' THEN 'CHINA'
WHEN country = 'Colombia' THEN 'COLOMBIA'
WHEN country = 'Croatia' THEN 'CROATIA'
WHEN country = 'Denmark' THEN 'DENMARK'
WHEN country = 'Ecuador' THEN 'ECUADOR'
WHEN country = 'Estonia' THEN 'ESTONIA'
WHEN country = 'Finland' THEN 'FINLAND'
WHEN country = 'France' THEN 'FRANCE'
WHEN country = 'Georgia' THEN 'GEORGIA'
WHEN country = 'Germany' THEN 'GERMANY'
WHEN country = 'Greece' THEN 'GREECE'
WHEN country = 'Hungary' THEN 'HUNGARY'
WHEN country = 'Iceland' THEN 'ICELAND'
WHEN country = 'India' THEN 'INDIA'
WHEN country = 'Ireland' THEN 'IRELAND'
WHEN country = 'Italy' THEN 'ITALY'
WHEN country = 'Kazakhstan' THEN 'KAZAKHSTAN'
WHEN country = 'Kenya' THEN 'KENYA'
WHEN country = 'Latvia' THEN 'LATVIA'
WHEN country = 'Lithuania' THEN 'LITHUANIA'
WHEN country = 'Mexico' THEN 'MEXICO'
WHEN country = 'Moldova' THEN 'MOLDOVA'
WHEN country = 'Netherlands' THEN 'NETHERLANDS'
WHEN country = 'New Zealand' THEN 'NEW ZEALAND'
WHEN country = 'Nigeria' THEN 'NIGERIA'
WHEN country = 'Norway' THEN 'NORWAY'
WHEN country = 'Paraguay' THEN 'PARAGUAY'
WHEN country = 'Peru' THEN 'PERU'
WHEN country = 'Poland' THEN 'POLAND'
WHEN country = 'Russia' THEN 'RUSSIA'
WHEN country = 'Serbia' THEN 'SERBIA'
WHEN country = 'Spain' THEN 'SPAIN'
WHEN country = 'Sweden' THEN 'SWEDEN'
WHEN country = 'Switzerland' THEN 'SWITZERLAND'
WHEN country = 'Tunisia' THEN 'TUNISIA'
WHEN country = 'Türkiye' THEN 'TURKEY'
WHEN country = 'Ukraine' THEN 'UKRAINE'
WHEN country = 'United Kingdom' THEN 'UK'
WHEN country = 'United States' THEN 'UNITED STATES'
WHEN country IN ('Albania', 'Andorra', 'Belarus', 'Bosnia & Herzegovina', 'Faroe Islands', 'Gibraltar', 'Guernsey', 'Isle of Man', 'Jersey', 'Kosovo', 'Liechtenstein', 'Monaco', 'Montenegro', 'North Macedonia', 'San Marino', 'Vatican City') THEN 'OTHER REST OF EUROPE NON-EU'
WHEN country IN ('American Samoa', 'Cook Islands', 'Fiji', 'French Polynesia', 'Guam', 'Kiribati', 'Marshall Islands', 'Micronesia', 'Nauru', 'New Caledonia', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Palau', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu') THEN 'REST OF WORLD OCEANIA - EXCL AU & NZ'
ELSE 'REST OF WORLD'
END AS CUSTOMER_MARKET_NAME
